### ISSUE TITLE
Self-hosting issues with Vercel/Netlify

### ISSUE THREAD

**Issue by efekrskl** [get-convex/convex-backend#162]
Hey everyone,

I recently started to self-host Convex for a project of mine. I wanted to use Vercel for deploying my frontend, but after replacing `CONVEX_DEPLOY_KEY` with `CONVEX_SELF_HOSTED_URL` & `CONVEX_SELF_HOSTED_ADMIN_KEY` the builds started to fail. Even though this is the suggested way of doing things in [self-hosting docs for Vercel and similar](https://github.com/get-convex/convex-backend/blob/main/self-hosted/README.md#deploying-your-frontend-app)

I went through the source code a bit, and it looks like `npm-packages/convex/src/cli/lib/deploymentSelection.ts:496` will always throw if `CONVEX_DEPLOY_KEY` is missing and `VERCEL` env variable exists (same for NETLIFY). Since Vercel ci sets this automatically this breaks all the builds. Disabling Automatically expose System Environment Variables in Vercel also didn't help.

My current workaround is to override the env var with `VERCEL="" npx convex deploy --cmd 'npm run build'` so process.env.VERCEL is falsy and the build continues as intended.

Curious if this is expected or something that could be improved. Happy to share more or open a PR if it helps.

**Comment by nipunn1313** [comment]
I'm not familiar with this issue. At the time those docs were written (a few months ago) they all worked. It's possible something regressed or changed.

Ideally you are able to just set the env vars and things should work.

If you could provide full repro steps and logs of the issue, that would help. And if the fix is obvious, PR would be welcome too.

**Comment by efekrskl** [comment]
Logs:

```
[16:55:29.579] Running build in Washington, D.C., USA (East) – iad1
[16:55:29.589] Build machine configuration: 2 cores, 8 GB
[16:55:29.668] Cloning github.com/efekrskl/******(Branch: main, Commit: 7c3780b)
[16:55:29.688] Skipping build cache, deployment was triggered without cache.
[16:55:31.169] Cloning completed: 1.501s
[16:55:31.713] Running "vercel build"
[16:55:33.881] Vercel CLI 44.5.0
[16:55:34.667] Installing dependencies...
[16:55:55.059] 
[16:55:55.059] added 491 packages in 20s
[16:55:55.060] 
[16:55:55.060] 147 packages are looking for funding
[16:55:55.060]   run `npm fund` for details
[16:55:55.123] Detected Next.js version: 15.3.4
[16:55:55.124] Running " npx convex deploy --cmd 'npm run build'"
[16:55:55.924] ✖ Vercel build environment detected but CONVEX_DEPLOY_KEY is not set. Set this environment variable to deploy from this environment. See https://docs.convex.dev/production/hosting
[16:55:55.945] Error: Command " npx convex deploy --cmd 'npm run build'" exited with 1
[16:55:56.267] 
[16:55:59.463] Exiting build container
```

This gets logged even though I had self hosted env variables in place (and removed `CONVEX_DEPLOY_KEY`)

Repro steps would be:
1) Create a project with Convex and host it in Vercel (mine was a Nextjs project)
2) Use the build command `npx convex deploy --cmd 'npm run build'` as suggested
3) Build will fail

Probably happens with Netlify too.

The fix would be probably easy, I'll take a look again when I have some free time

**Comment by nipunn1313** [comment]
I think `CONVEX_DEPLOY_KEY` is a special key that is needed by the CLI. I don't think it would be different for self-hosting, since as far as the frontend is concerned, there's no real difference between cloud or self hosted backend other than the URL and deploy key.

Take a look inside deploymentSelection.ts to make sure.

It seems like it should all be workable. It's possible the self-host instructions are off.

**Comment by efekrskl** [comment]
We fixed this in https://github.com/get-convex/convex-backend/commit/0f608bab37e9bacb1f646075973b52bce142768c

**Comment by cliffordkleinsr** [comment]
I don't believe this was pushed to npm. I am still facing this issue on both Vercel & Netlify

<img width="1340" height="810" alt="Image" src="https://github.com/user-attachments/assets/d73e7ec9-a3a1-4d66-8de3-ffeb970c802e" />
