### ISSUE TITLE
Error when running 'npx convex dev' command for self-hosted convex backend

### ISSUE THREAD

**Issue by AayushGaRrg** [get-convex/convex-backend#200]
I am hosting my own convex backend. When trying to run the npx convex dev command with the schema.ts file being there I get the following error message in the terminal and I get two lines in the terminal : 
```
⠏ Preparing Convex functions...
⠹ Checking for index or schema changes....
```

If I delete the schema file and then run the command then it does not error out but when I add back the schema.ts file I get the following error:
```
✔ Added table indexes:
  [+] todos.by_completed ["completed","_creationTime"]
Unexpected Error: TypeError: Cannot read properties of undefined (reading 'length')

```and the function stops.
Below are the content of the files:

schema.ts
```
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// Data model for a single-user Todo app
export default defineSchema({
  todos: defineTable({
    text: v.string(),
    completed: v.boolean(),
  }).index("by_completed", ["completed"]), // for clearing completed
});
```

todo.ts
```
import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

export const list = query({
  args: {},
  handler: async (ctx) => {
    const todos = await ctx.db.query("todos").order("asc").collect();
    return todos;
  },
});

export const add = mutation({
  args: { text: v.string() },
  handler: async (ctx, args) => {
    const text = args.text.trim();
    if (text.length === 0) {
      throw new Error("Text is required");
    }
    const id = await ctx.db.insert("todos", {
      text,
      completed: false,
    });
    return id;
  },
});

export const toggle = mutation({
  args: { id: v.id("todos"), completed: v.boolean() },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.id, { completed: args.completed });
  },
});

export const clearCompleted = mutation({
  args: {},
  handler: async (ctx) => {
    const completed = await ctx.db
      .query("todos")
      //   .withIndex("by_completed", (q) => q.eq("completed", true))
      .collect();
    for (const todo of completed) {
      await ctx.db.delete(todo._id);
    }
    return completed;
  },
});
```
I am hosting my own convex backend. When trying to run the npx convex dev command with the schema.ts file being there I get the following error message in the terminal and I get two lines in the terminal : 
⠏ Preparing Convex functions...
⠹ Checking for index or schema changes....

If I delete the schema file and then run the command then it does not error out but when I add back the schema.ts file I get the following error:
✔ Added table indexes:
  [+] todos.by_completed ["completed","_creationTime"]
Unexpected Error: TypeError: Cannot read properties of undefined (reading 'length')
and the function stops.
Below are the content of the files:

schema.ts
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// Data model for a single-user Todo app
export default defineSchema({
  todos: defineTable({
    text: v.string(),
    completed: v.boolean(),
  }).index("by_completed", ["completed"]), // for clearing completed
});

todo.ts
import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

export const list = query({
  args: {},
  handler: async (ctx) => {
    const todos = await ctx.db.query("todos").order("asc").collect();
    return todos;
  },
});

export const add = mutation({
  args: { text: v.string() },
  handler: async (ctx, args) => {
    const text = args.text.trim();
    if (text.length === 0) {
      throw new Error("Text is required");
    }
    const id = await ctx.db.insert("todos", {
      text,
      completed: false,
    });
    return id;
  },
});

export const toggle = mutation({
  args: { id: v.id("todos"), completed: v.boolean() },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.id, { completed: args.completed });
  },
});

<img width="1001" height="162" alt="Image" src="https://github.com/user-attachments/assets/986077a5-0fd3-459c-a9a3-7c57da7db963" />


export const clearCompleted = mutation({
  args: {},
  handler: async (ctx) => {
    const completed = await ctx.db
      .query("todos")
      //   .withIndex("by_completed", (q) => q.eq("completed", true))
      .collect();
    for (const todo of completed) {
      await ctx.db.delete(todo._id);
    }
    return completed;
  },
});

**Comment by thomasballinger** [comment]
@AayushGaRrg what version of convex are you using, this sounds like a bug in 1.26.0 that was fixed in 1.26.1

**Comment by MarcRibasG** [comment]
The same thing happened to me yesterday, I downgraded to 1.25.4 amd the problem was solved, but now Im having some problems with the docker image too...

**Comment by AayushGaRrg** [comment]
@thomasballinger  the bug is still present in the version 1.26.1. I also downgraded it to 1.25.4 to resolve the issue.

**Comment by thomasballinger** [comment]
Thanks @MarcRibasG and @AayushGaRrg, could you share more info here? What do I need to do to repro? What backend version are you using?

Specifically, how have you set up self-hosting?

**Comment by daraeowl** [comment]
> Thanks [@MarcRibasG](https://github.com/MarcRibasG) and [@AayushGaRrg](https://github.com/AayushGaRrg), could you share more info here? What do I need to do to repro? What backend version are you using?
> 
> Specifically, how have you set up self-hosting?


Same error here with the dokploy template:
```
services:
  backend:
    image: ghcr.io/get-convex/convex-backend:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME:-}
      - INSTANCE_SECRET=${INSTANCE_SECRET:-}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV:-}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS:-}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN:-http://127.0.0.1:3210}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN:-http://127.0.0.1:3211}
      - DATABASE_URL=${DATABASE_URL:-}
      - DISABLE_BEACON=${DISABLE_BEACON:-}
      - REDACT_LOGS_TO_CLIENT=${REDACT_LOGS_TO_CLIENT:-}
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-}
    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 5s

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:3210}
    depends_on:
      backend:
        condition: service_healthy

volumes:
  data:
```
edit: it was fixed with

```services:
  backend:
    image: ghcr.io/get-convex/convex-backend:6efab6f2b6c182b90255774d747328cfc7b80dd9
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME:-}
      - INSTANCE_SECRET=${INSTANCE_SECRET:-}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV:-}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS:-}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN:-http://127.0.0.1:3210}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN:-http://127.0.0.1:3211}
      - DATABASE_URL=${DATABASE_URL:-}
      - DISABLE_BEACON=${DISABLE_BEACON:-}
      - REDACT_LOGS_TO_CLIENT=${REDACT_LOGS_TO_CLIENT:-}
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-}
    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 5s

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:6efab6f2b6c182b90255774d747328cfc7b80dd9
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:3210}
    depends_on:
      backend:
        condition: service_healthy

volumes:
  data:
```

**Comment by AmrAbuElyazid** [comment]
I’m seeing the same issue on macOS with a self-hosted Convex backend. Fresh Next.js project, using the Chat example from the docs.


With schema.ts present:
```bash
❯ CONVEX_VERBOSE=1 npx convex dev
# ...
Unexpected Error: TypeError: Cannot read properties of undefined (reading 'length')
⠸ Checking for index or schema changes...
```
Then the process exits immediately.

Environment:
- convex CLI 1.26.1
- Node 23 / macOS (self-hosted backend)

Workarounds I found:

- Removing schema.ts avoids the crash but obviously loses schema sync.
- Downgrading CLI by running `npx convex@1.25 dev` works fine, so this seems like a regression after 1.25. 

Let me know if logs or a minimal reproduction would help — happy to provide them.

**Comment by jjrise** [comment]
> `npx convex@1.25 dev`

@AmrAbuElyazid you are the best - that worked for me as well... similar situation with macOS with self hosted Convex, but with Tanstack Start.

**Comment by MarcRibasG** [comment]
I'm deploying convex on a k3s cluster (ubuntu 24.04 ), the latest image release seems to work fine (but now just in case using 6efab...b80dd9  ), CLI (ubuntu 24.04) with the new version (1.26.1) doesn't work on deploying the schema. I think it's not related to any kind of OS.

**Comment by AmrAbuElyazid** [comment]
Could you please confirm if you have a `tsconfig.json` inside the convex folder? If not, could you try this `tsconfig.json` with the latest CLI version? 

```{
  "compilerOptions": {
    "allowJs": true,
    "strict": true,
    "moduleResolution": "Bundler",
    "jsx": "react-jsx",
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,

    "target": "ESNext",
    "lib": ["ES2021", "dom"],
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["./**/*"],
  "exclude": ["./_generated"]
}
```

**Comment by AayushGaRrg** [comment]
> Could you please confirm if you have a `tsconfig.json` inside the convex folder? If not, could you try this `tsconfig.json` with the latest CLI version?
> 
> ```
>   "compilerOptions": {
>     "allowJs": true,
>     "strict": true,
>     "moduleResolution": "Bundler",
>     "jsx": "react-jsx",
>     "skipLibCheck": true,
>     "allowSyntheticDefaultImports": true,
> 
>     "target": "ESNext",
>     "lib": ["ES2021", "dom"],
>     "forceConsistentCasingInFileNames": true,
>     "module": "ESNext",
>     "isolatedModules": true,
>     "noEmit": true
>   },
>   "include": ["./**/*"],
>   "exclude": ["./_generated"]
> }
> ```

I am making the project in a react app so there is no tsconfig.json in the convex folder. I don't think there should be one in that folder also. Should I change use this configuration in the main tsconfig.json?

**Comment by AmrAbuElyazid** [comment]
> I am making the project in a react app so there is no tsconfig.json in the convex folder. I don't think there should be one in that folder also. Should I change use this configuration in the main tsconfig.json?

Try adding `./convex` in your main tsconfig's include in the root directory?
```
"include": ["./src", "./convex", "vite.config.mts"]
```

**Comment by AayushGaRrg** [comment]
> Thanks [@MarcRibasG](https://github.com/MarcRibasG) and [@AayushGaRrg](https://github.com/AayushGaRrg), could you share more info here? What do I need to do to repro? What backend version are you using?
> 
> Specifically, how have you set up self-hosting?

I am using the latest docker-compose file and running the file locally on my system. I have followed the steps mentioned in the docs. Downloading the file, running `docker compose up` and getting the admin key to login.  Here is the file configuration: 
```
services:
  backend:
    image: ghcr.io/get-convex/convex-backend:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - data:/convex/data
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME:-}
      - INSTANCE_SECRET=${INSTANCE_SECRET:-}
      - CONVEX_RELEASE_VERSION_DEV=${CONVEX_RELEASE_VERSION_DEV:-}
      - ACTIONS_USER_TIMEOUT_SECS=${ACTIONS_USER_TIMEOUT_SECS:-}
      - CONVEX_CLOUD_ORIGIN=${CONVEX_CLOUD_ORIGIN:-http://127.0.0.1:${PORT:-3210}}
      - CONVEX_SITE_ORIGIN=${CONVEX_SITE_ORIGIN:-http://127.0.0.1:${SITE_PROXY_PORT:-3211}}
      - DATABASE_URL=${DATABASE_URL:-}
      - DISABLE_BEACON=${DISABLE_BEACON:-}
      - REDACT_LOGS_TO_CLIENT=${REDACT_LOGS_TO_CLIENT:-}
      - DO_NOT_REQUIRE_SSL=${DO_NOT_REQUIRE_SSL:-}
      - POSTGRES_URL=${POSTGRES_URL:-}
      - MYSQL_URL=${MYSQL_URL:-}
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-}
      - AWS_REGION=${AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      - AWS_S3_FORCE_PATH_STYLE=${AWS_S3_FORCE_PATH_STYLE:-}
      - S3_STORAGE_EXPORTS_BUCKET=${S3_STORAGE_EXPORTS_BUCKET:-}
      - S3_STORAGE_SNAPSHOT_IMPORTS_BUCKET=${S3_STORAGE_SNAPSHOT_IMPORTS_BUCKET:-}
      - S3_STORAGE_MODULES_BUCKET=${S3_STORAGE_MODULES_BUCKET:-}
      - S3_STORAGE_FILES_BUCKET=${S3_STORAGE_FILES_BUCKET:-}
      - S3_STORAGE_SEARCH_BUCKET=${S3_STORAGE_SEARCH_BUCKET:-}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL:-}

    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 10s

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:33cef775a8a6228cbacee4a09ac2c4073d62ed13
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=${NEXT_PUBLIC_DEPLOYMENT_URL:-http://127.0.0.1:${PORT:-3210}}
    depends_on:
      backend:
        condition: service_healthy

volumes:
  data:
```

**Comment by thomasballinger** [comment]
Following https://github.com/get-convex/convex-backend/blob/main/self-hosted/README.md I copied down the linked docker-compose.yml file into an empty directory and ran `docker compose up`.

Then I created a new project with `npm create convex@latest` (vite, no auth), `cd my-app`, created an .env.local file with the two environment variables as instructed, and ran `npx convex dev` to see the crash:

```
tomb@macbookpro my-app % CONVEX_VERBOSE=1 npx convex dev
[verbose] 2025-08-27T16:23:47.079Z Updating big brain auth to accessToken
[verbose] 2025-08-27T16:23:47.080Z Existing deployment: http://127.0.0.1:3210 selfHosted
[verbose] 2025-08-27T16:23:47.165Z Skipping non-JS file convex/README.md
[verbose] 2025-08-27T16:23:47.166Z Skipping convex/_generated/api.d.ts
[verbose] 2025-08-27T16:23:47.166Z Skipping convex/_generated/api.js
[verbose] 2025-08-27T16:23:47.166Z Skipping convex/_generated/dataModel.d.ts
[verbose] 2025-08-27T16:23:47.166Z Skipping convex/_generated/server.d.ts
[verbose] 2025-08-27T16:23:47.166Z Skipping convex/_generated/server.js
[verbose] 2025-08-27T16:23:47.166Z Preparing convex/myFunctions.ts
[verbose] 2025-08-27T16:23:47.166Z Skipping convex/schema.ts
[verbose] 2025-08-27T16:23:47.166Z Skipping non-JS file convex/tsconfig.json
[verbose] 2025-08-27T16:23:47.964Z Skipping non-JS file convex/README.md
[verbose] 2025-08-27T16:23:47.964Z Skipping convex/_generated/api.d.ts
[verbose] 2025-08-27T16:23:47.964Z Skipping convex/_generated/api.js
[verbose] 2025-08-27T16:23:47.964Z Skipping convex/_generated/dataModel.d.ts
[verbose] 2025-08-27T16:23:47.964Z Skipping convex/_generated/server.d.ts
[verbose] 2025-08-27T16:23:47.964Z Skipping convex/_generated/server.js
[verbose] 2025-08-27T16:23:47.964Z Preparing convex/myFunctions.ts
[verbose] 2025-08-27T16:23:47.964Z Skipping convex/schema.ts
[verbose] 2025-08-27T16:23:47.964Z Skipping non-JS file convex/tsconfig.json
[verbose] 2025-08-27T16:23:47.993Z Found no auth config file at /Users/tomb/self-hosting/my-app/convex/auth.config.ts or /Users/tomb/self-hosting/my-app/convex/auth.config.js so there are no
configured auth providers
Unexpected Error: TypeError: Cannot read properties of undefined (reading 'length')
⠸ Checking for index or schema changes...
tomb@macbookpro my-app %
```

Annoying there's no stack trace! This looks easy to fix, expect a client release today with a fix.

**Comment by thomasballinger** [comment]
Got a fix, will roll this out at 1.26.2 later today.

The workaround suggested upthread of using convex@1.25.4 is the right approach here, hang in there with the old client.

For the future know that using new CLI versions against old deployments is not supported indefinitely; if you don't upgrade your backend deployment, you will need to stop upgrading your CLI. But this happened too quickly here. The currently released CLI should always support the currently released official docker-compose self-hosted setup, and without this fix it does not, so this is a bug.

**Comment by thomasballinger** [comment]
Convex 1.26.2 it out with the fix

**Comment by jjrise** [comment]
awesome thanks @thomasballinger ... 1.26.2 worked for me initially, but now giving me the following error. Similarly, if I run `npx convex@1.25 dev` it will run normally.

```
✖ esbuild failed: Error: The service was stopped: write EPIPE
```

**Comment by thomasballinger** [comment]
@jjrise hm, what operating system? There are some cases of esbuild binary mismatch causing this, but I don't know of changes between 1.25 and 1.26.2 causing this.
Could you open a new issue and share your operating system and setup, like whether you're using docker or a binary and where you're running the `npx convex` comment?
